# Generated by Django 4.0.1 on 2022-02-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_likes_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='post',
            new_name='posts',
        ),
    ]
