# Generated by Django 4.0.1 on 2022-02-19 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_post_likes_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='followed',
        ),
        migrations.AddField(
            model_name='follows',
            name='follows',
            field=models.ManyToManyField(related_name='are_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follows',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='are_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likes',
            name='posts',
            field=models.ManyToManyField(related_name='are_liked', to='network.Posts'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='are_liking', to=settings.AUTH_USER_MODEL),
        ),
    ]
