# Generated by Django 4.0.1 on 2022-02-20 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_follows_followed_follows_follows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='follows',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likes',
            name='posts',
            field=models.ManyToManyField(related_name='likers', to='network.Posts'),
        ),
    ]
